### ISSUE TITLE
Incorrect editor address when creating “new document ” on confluence attachment page

### ISSUE THREAD

**Issue by lumos0** [ONLYOFFICE/onlyoffice-confluence#116]
same as https://forum.onlyoffice.com/t/incorrect-editor-address-when-creating-new-document-on-confluence-attachment-page/7138
---

when creating "new document " on confluence attachment page,

![image](https://github.com/ONLYOFFICE/onlyoffice-confluence/assets/30490759/445304cf-84e0-4bf5-bba9-34dbcd55d338)

click √， the browser will open this url in a new tab,

https://conf.com/plugins/servlet/onlyoffice/?attachmentId=xxxxxxx
the new tab page shows “page not found” , it seems because missing “doceditor” in url . the new tab url should be

https://conf.com/plugins/servlet/onlyoffice/doceditor?attachmentId=xxxxxxx
Document Server version: 7.5.1
Connector version: 4.4
DMS (platform) version: confluence 7.13

**Comment by alexanderonlyoffice** [comment]
Hello @lumos0, this issue was fixed on develop branch, please try out this [artifact](https://github.com/ONLYOFFICE/onlyoffice-confluence/actions/runs/7286312951) and let us know if the issue still persists.

**Comment by lumos0** [comment]
> Hello @lumos0, this issue was fixed on develop branch, please try out this [artifact](https://github.com/ONLYOFFICE/onlyoffice-confluence/actions/runs/7286312951) and let us know if the issue still persists.

it works
