### ISSUE TITLE
Update for Confluence 9.0 with Java 21

### ISSUE THREAD

**Issue by T-Herrmann-WI** [ONLYOFFICE/onlyoffice-confluence#135]
Update for Confluence 9.0 with Java 21

**Comment by tobilektri** [comment]
@LinneyS is there a timeline when the Update will be available?

**Comment by tobilektri** [comment]
@LinneyS any news?

**Comment by aleksandrfedorov97** [comment]
Hello [tobilektri](https://github.com/tobilektri), we have prepared changes that make our plugin compatible with confluence 9. Now these changes are in the testing stage and we will make a release in the near future. [feature/confluence-9](https://github.com/ONLYOFFICE/onlyoffice-confluence/tree/feature/confluence-9)

**Comment by aleksandrfedorov97** [comment]
[cc15a130d1fe7d50553cff9bc1a9220f0c6c827a](https://github.com/ONLYOFFICE/onlyoffice-confluence/commit/cc15a130d1fe7d50553cff9bc1a9220f0c6c827a)
