### ISSUE TITLE
Cannot use it with Secret

### ISSUE THREAD

**Issue by michaelroth** [ONLYOFFICE/onlyoffice-confluence#4]
I've installed the OnlyOffice DocumentServer Version 5.0.4.15 and OnlyOffice Confluence Plugin Version 1.1.0 on Confluence 6.4.2

This is the way I create the Confluence plugin

$ git clone https://github.com/ONLYOFFICE/onlyoffice-confluence
Changed the properties in src/main/resources/onlyoffice-config.properties

files.docservice.secret=secret

$ atlas-package

Then I installed the plugin by uploading it into Confluence
I configured the plugin in Manage add-ons

If I try to edit a document Confluence opens a new tab in my browser and connects to the my document server, then  I got the following error message.

Java.lang.Exception: Error occured in the Convertservice: Error document VKey

If I turn off the Secret Usage on my Document Server everything works. I will use the Secret because I don't want that everybody can use my Document Server.

**Comment by alexanderonlyoffice** [comment]
Hello @michaelroth,

Plugin for Confluence is not refined yet. In this case, Secret is being used for safety of the files downloaded from Confluence, it was made to limit access to the files of Confluence.

We keep on working on support of JWT.

**Comment by LinneyS** [comment]
6429fe57977c4b9349b7de0a3517604fbb7f338c
Please, use [v2.0.0](https://github.com/ONLYOFFICE/onlyoffice-confluence/releases/tag/v2.0)
