### ISSUE TITLE
"Edit on Only Office" not showing

### ISSUE THREAD

**Issue by Zasig** [ONLYOFFICE/onlyoffice-confluence#5]
Hello,

we recently tested a new confluence version and installed the add-on, we setup a document editor server and it worked.
Confluence Version 6.7.2

Now we deployed a new confluence appliance, installed the add-on and no attachment is showing the "Edit in Only Office" context.

Confluence is the same Version as in the lab scenario and the add-on is loaded and active. it's just showing it's outdated but that was also showing in the lab setup - but it worked.
Is there anything that we might have done to disable this add-on? Or is there a log to lookup a possible error?

Kind regards,

Max

**Comment by alexanderonlyoffice** [comment]
Hello @Zasig, unfortunately, we did not develop and test ONLYOFFICE application for the version 6.7.2 of Confluence and we do not know how the application may behave.

**Comment by Zasig** [comment]
i tried a few things and i noticed that the files i upload were not recognized as edit/viewable items for die document server. Because of that, it didn't show the string.
